# Generated by Django 3.2.6 on 2021-11-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appetment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='petprofile',
            name='pet_image',
            field=models.URLField(default='https://lh3.googleusercontent.com/4QEa2v4huepda_QVp8eg0uWw2XyB1KCQ54JmrD5KAdhdzn5SoBesFkYxvzZtPrt2BEdLTM1tWcOZJk5g2HTnVgZT948PsJlWVqeXUTVJFE3DAaaqhiS-L7TaPSuHz3qnwGqMzQ2p_WkSejHfxzNsq9AH7cPw48jYC9fJ1fIwRWANXPrQ-J_x81kOtBsmGhKncQmdxyz5IYNo1jSREGek8bMnYMG0ghWolSKjFZwbMWhE-zTKRyg9HFcBbnZpwe0WMtgFA5Hs21sZ_YPo-7op46k2D61PnsYww2wLvFwOD1vvGSQMvYTk3RadpeIZuAX9qBiF8gj3IFhh4aWn5e34jVfTsoYOTU7mWU7tgdmkJ1fn8W6vOemWpTdSoRhAzOcjG0AZKvvg6OBuqehKdxMTmGDmeSEfqUPa2gk0yPPtOqO-4XAURG3h1a4g4TiSo2jdGFqIANHIs8pf7_xMrjsFaR1AIcijulViqx-cPpETyqB92tf-d9TA9M7gkTirElSEWzaPSwybkG03X1EzfUJY1OYCuWSeqjFAFpXG0mX8VWFRNUW2dkUFPvwsJna9lVlZ1KF3PXv86zi0WbB4PCLUqXuazAKaP8u01MCqAyjMgzbMWnD3O5rLA1gYKS2OljhZJYYw_YONQ7kZb3PTSBCA97c2mUYbZXb-1fjkQZGefP8ynVcMhMRizjzg5g4tCGK3f7AK4tCYFRqvPEJfR7lQKUs=s300-no?authuser=0'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vetappointment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
